"""Compatibility re-export for the split GS1 host package."""
import importlib as _importlib
import sys as _sys

_target = _importlib.import_module(".gs1.host", __package__)
_leaves = ('host', 'builtins', 'commands.character', 'commands.world', 'commands.combat', 'commands.visual', 'commands', 'execution', 'players')
_names = ['CarryObjectSprite', 'Context', 'GS1Host', 'GS1_EXPLOSION_PLAYERS', 'Host', 'Interpreter', 'LEVEL_SIZE', 'LEVEL_TILE_COUNT', 'NPCPROP', 'NPC_ATTR', 'NPC_CHARPROP', 'PLAYER_ATTR', 'PLAYER_CHARPROP', 'PLAYER_PROP_WIRE', 'PLPROP', 'UNSET', 'VarStore', '_BUILTINS', '_CARRY_SPRITE', '_CHARPROP_CODES', '_CLASSIC_COLORS', '_CLASSIC_COLOR_INDEX', '_COLOR_CODE_RE', '_COMMANDS', '_GANI_ATTR_RE', '_GS1_ERR_SEEN', '_NOOP_COMMANDS', '_NPC_GATTRIB_PROPS', '_NW_CLOCK_FIELDS', '_NW_EPOCH', '_PELTWITH_TYPE', '_PLAYER_GATTRIB_PROPS', '_PendingGS1Sleep', '_SHOTBY_SOURCE', '__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_apply_charprop', '_b_board', '_b_carries_object', '_b_carriesnpc', '_b_carrying', '_b_compsdead', '_b_isleader', '_b_isonmap', '_b_isweapon', '_b_nw_clock', '_b_peltwith', '_b_player_gender', '_b_playerfreezetime', '_b_playerlevel', '_b_playeronhorse', '_b_playeronline', '_b_playerswimming', '_b_shotby', '_b_sprite', '_b_tiles', '_b_timeout', '_b_timevar2', '_b_tokenscount', '_b_visible', '_b_weaponsenabled', '_bind_fresh_gs1_call', '_broadcast_showimgs', '_c_addweapon', '_c_canbecarried', '_c_canbepulled', '_c_canbepushed', '_c_cannotbecarried', '_c_cannotbepulled', '_c_cannotbepushed', '_c_carryobject', '_c_changeimgcolors', '_c_changeimgmode', '_c_changeimgpart', '_c_changeimgvis', '_c_changeimgzoom', '_c_destroy', '_c_disableweapons', '_c_enableweapons', '_c_freezeplayer', '_c_hide', '_c_hideimg', '_c_hitcompu', '_c_hitnpc', '_c_hitobjects', '_c_hitplayer', '_c_hurt', '_c_lay', '_c_lay2', '_c_message', '_c_move', '_c_noop', '_c_putbomb', '_c_putexplosion', '_c_putexplosion2', '_c_puthorse', '_c_putnpc', '_c_putnpc2', '_c_say2', '_c_sendtorc', '_c_setani', '_c_setbeltcolor', '_c_setbody', '_c_setchargender', '_c_setcharprop', '_c_setcoatcolor', '_c_setgender', '_c_sethead', '_c_setimg', '_c_setimgpart', '_c_setlevel', '_c_setlevel2', '_c_setnick', '_c_setplayerdir', '_c_setplayerprop', '_c_setshape', '_c_setshield', '_c_setshoecolor', '_c_setskincolor', '_c_setsleevecolor', '_c_setsword', '_c_shootarrow', '_c_show', '_c_showcharacter', '_c_showimg', '_c_take', '_c_takehorse', '_c_takeplayercarry', '_c_throwcarry', '_c_toweapons', '_c_triggeraction', '_c_unfreezeplayer', '_c_updateboard', '_change_showimg', '_charprop_target', '_ensure_gs1_ctx', '_explode', '_explosion_targets', '_flush_player_props', '_gattribs_of', '_lazy', '_make_blockflag_cmd', '_make_color_cmd', '_name', '_normalized_push', '_nw_clock_value', '_player_hurt_push', '_queue_player_prop', '_report_gs1_error', '_resolve_color', '_schedule', '_set_player_color', '_showimg_index', '_spawn_item', '_spawn_npc', 'annotations', 'asyncio', 'compile_gs1', 'contains', 'leader_player_for_level', 'level_index', 'logger', 'logging', 'math', 'parse', 'players_on_level_for', 're', 'run_npc_event', 'segment_index', 'tiletypes', 'time', 'to_num', 'to_str']
for _leaf in _leaves:
    _module = _importlib.import_module(".gs1." + _leaf, __package__)
    for _export in _names:
        if hasattr(_module, _export):
            setattr(_target, _export, getattr(_module, _export))
for _temporary in (
    "_importlib", "_sys", "_target", "_leaves", "_names", "_leaf",
    "_module", "_export", "_temporary",
):
    _target.__dict__.pop(_temporary, None)
_sys.modules[__name__] = _target
