#!/usr/bin/env python3
"""Generate pygserver/pygserver/gs1/_tables.py from the GServer-v2 ANTLR grammar.

The C++ engine is the spec (see memory: gs1-python-port). Rather than hand-copy
206 commands / 65 functions and their per-argument lexer-mode strings, we parse
them straight out of grammar/GS1Lexer.g4 so the Python port stays faithful and
can be regenerated when the grammar changes.

Usage:
    python tools/gen_gs1_tables.py [path/to/GS1Lexer.g4]

Arg-type strings (the chars after pushCommand) drive the context-sensitive lexer,
one char per argument slot:
    V variable   E expression   S string   R raw-string   L rest-of-line/list
    M messagecode  D direction   I item     G gender       Z npc-script-body
    U carry-object  P param      ( ) < grouping/comma markers (functions)
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_GRAMMAR = os.path.normpath(os.path.join(
    HERE, "..", "..", "GServer-v2", "server", "src", "scripting", "gs1",
    "grammar", "GS1Lexer.g4"))
OUT = os.path.normpath(os.path.join(HERE, "..", "pygserver", "gs1", "_tables.py"))

# CMD_X : 'literal'  [{ pushCommand("ARGS"); }]  -> type(COMMAND);
CMD_RE = re.compile(
    r"""^\s*CMD_\w+\s*:\s*'([^']*)'\s*(?:\{\s*pushCommand\("([^"]*)"\)\s*;\s*\})?\s*->\s*type\(COMMAND\)""",
    re.M)

# MC_X : '#x...' [{ pushCommand("ARGS"); }] -> type(MESSAGECODE);  (base defs, not PARAM_* copies)
MC_RE = re.compile(
    r"""^MC_\w+\s*:\s*'([^']*)'\s*(?:\{\s*pushCommand\("([^"]*)"\)\s*;\s*\})?\s*->\s*type\(MESSAGECODE\)""",
    re.M)

# FUNC_GROUP_N : ( 'a' | 'b' | ... ) { pushCommand("(ARGS)"); } -> type(FUNCTION)
# Names may be a parenthesised alternation or a single bare 'name'.
FUNC_RE = re.compile(
    r"""FUNC_GROUP_\d+\s*:\s*(\(.*?\)|'[^']*')\s*\{\s*pushCommand\("([^"]*)"\)\s*;\s*\}\s*->\s*type\(FUNCTION\)""",
    re.S)

NAME_RE = re.compile(r"'([^']*)'")


def parse(grammar_path):
    text = open(grammar_path, encoding="utf-8").read()

    commands = {}
    for lit, args in CMD_RE.findall(text):
        # trailing space in the literal ('set ', 'say ') means the command token
        # requires a following separator; record the bare name + that flag.
        name = lit.rstrip(" ")
        commands[name] = {"args": args, "needs_space": lit.endswith(" ")}

    messagecodes = {}
    for lit, args in MC_RE.findall(text):
        messagecodes[lit] = args  # e.g. '#s' -> '(V)'

    functions = {}
    for names_blob, args in FUNC_RE.findall(text):
        for name in NAME_RE.findall(names_blob):
            functions[name] = args  # e.g. 'onwall' -> '(P)'

    return commands, messagecodes, functions


def render(commands, messagecodes, functions):
    def dump_dict(d, valfmt):
        return "".join(f"    {k!r}: {valfmt(v)},\n" for k, v in sorted(d.items()))

    lines = []
    lines.append('"""GS1 lexer tables — AUTO-GENERATED by tools/gen_gs1_tables.py.\n')
    lines.append("Do not edit by hand; regenerate from GServer-v2/.../GS1Lexer.g4.\n")
    lines.append('See memory: gs1-python-port. Arg-type chars documented in the generator.\n"""\n')
    lines.append("# command name -> {'args': mode-string, 'needs_space': bool}\n")
    lines.append("COMMANDS = {\n")
    lines.append(dump_dict(commands, lambda v: repr(v)))
    lines.append("}\n\n")
    lines.append("# builtin function name -> arg mode-string (parenthesised form)\n")
    lines.append("FUNCTIONS = {\n")
    lines.append(dump_dict(functions, lambda v: repr(v)))
    lines.append("}\n\n")
    lines.append("# message code literal (e.g. '#s') -> arg mode-string, or '' if none\n")
    lines.append("MESSAGECODES = {\n")
    lines.append(dump_dict(messagecodes, lambda v: repr(v)))
    lines.append("}\n")
    return "".join(lines)


def main():
    grammar = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_GRAMMAR
    commands, messagecodes, functions = parse(grammar)
    out = render(commands, messagecodes, functions)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(out)
    print(f"grammar: {grammar}")
    print(f"wrote:   {OUT}")
    print(f"  commands={len(commands)} functions={len(functions)} messagecodes={len(messagecodes)}")


if __name__ == "__main__":
    main()
